CUSTOM_BRAND := TheParasiteProject

CUSTOM_BUILD_DATE := $(shell date +%Y%m%d-%H%M)
CUSTOM_BUILD_DATE_UTC := $(shell date '+%Y-%m-%d %H:%M UTC %s')
CUSTOM_BUILD_VERSION := $(BUILD_ID)
CUSTOM_RELEASETYPE ?= release

CUSTOM_VERSION := $(CUSTOM_BRAND)_$(LINEAGE_BUILD)-$(BUILD_ID)-$(CUSTOM_BUILD_DATE)

PRODUCT_BRAND := $(CUSTOM_BRAND)
LINEAGE_BUILD_DATE := $(CUSTOM_BUILD_DATE)
LINEAGE_BUILDTYPE := $(CUSTOM_RELEASETYPE)
LINEAGE_VERSION := $(CUSTOM_VERSION)
LINEAGE_DISPLAY_VERSION := $(CUSTOM_BUILD_VERSION)

# Versioning props
PRODUCT_SYSTEM_PROPERTIES += \
    ro.custom.brand=$(PRODUCT_BRAND) \
    ro.custom.build.version=$(PLATFORM_DISPLAY_VERSION).$(CUSTOM_BUILD_VERSION) \
    ro.custom.display.version=$(LINEAGE_DISPLAY_VERSION) \
    ro.custom.releasetype=$(LINEAGE_BUILDTYPE) \
    ro.custom.version=$(LINEAGE_VERSION) \
    ro.modversion=$(LINEAGE_VERSION)
