flag_value {
  package: "com.android.systemui"
  name: "new_volume_panel"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "screenshot_ui_controller_refactor"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "status_bar_screen_sharing_chips"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "app_clips_backlinks"
  state: ENABLED
  permission: READ_ONLY
}
