#!/bin/bash

GREEN="\033[0;32m"

Changelog="changelog.md"

DEVICE=$1
if [ -z $DEVICE ]; then
	DEVICE=$(echo $TARGET_PRODUCT | sed -e 's/lineage_//g')
fi

CHANGELOG_DAYS=$2
if [ -z $CHANGELOG_DAYS ];then
	CHANGELOG_DAYS=5
else
	if (($CHANGELOG_DAYS > 30 )); then
        echo "Changelog cannot be generated for periods exceeding 30 days. Please specify a shorter time frame. (Timeout: 15 seconds - defaulting to 5 days)"
        read -r -t 15 CHANGELOG_DAYS || CHANGELOG_DAYS=5
	fi
fi

if [ -f $Changelog ];
then
	rm -f $Changelog
fi

touch $Changelog

echo -e "# $DEVICE\n" >> $Changelog;

for i in $(seq $CHANGELOG_DAYS);
do
	export After_Date=`/bin/date --date="$i days ago" +%m-%d-%Y`
	k=$(expr $i - 1)
	export Until_Date=`/bin/date --date="$k days ago" +%m-%d-%Y`
	echo -e "### $Until_Date\n" >> $Changelog;
	# Cycle through every repo to find commits between 2 dates
	CURRENT_PATH="$(realpath `pwd`)"
    repo forall -c "GIT_LOG=\`git log --oneline --after=$After_Date --until=$Until_Date --pretty=tformat:"%x2A %h  %s  [%an]" --abbrev-commit --abbrev=7\` ; if [ -n \"\$GIT_LOG\" ]; then echo -e \"#### ${path}\\n\\n\$GIT_LOG\\n\" ; fi >> $Changelog"
done

cp $Changelog ${OUT_DIR:-./out}/target/product/$DEVICE/
rm $Changelog
echo -e "${GREEN}Done generating changelog for $DEVICE"

unset GREEN Changelog DEVICE
