#!/bin/bash

GREEN="\033[0;32m"

CHANGELOG="changelog.md"

DEVICE=$1
if [ -z $DEVICE ]; then
	DEVICE=$(echo $TARGET_PRODUCT | sed -e 's/lineage_//g')
fi

CHANGELOG_DAYS=$2
if [ -z $CHANGELOG_DAYS ];then
	CHANGELOG_DAYS=5
else
	if (($CHANGELOG_DAYS > 30 )); then
        echo "Changelog cannot be generated for periods exceeding 30 days. Please specify a shorter time frame. (Timeout: 15 seconds - defaulting to 5 days)"
        read -r -t 15 CHANGELOG_DAYS || CHANGELOG_DAYS=5
	fi
fi

if [ -f $CHANGELOG ];
then
	rm -f $CHANGELOG
fi

touch $CHANGELOG

REPO_LIST="$(repo list --path)"
for i in $(seq $CHANGELOG_DAYS); do
	export After_Date=`/bin/date --date="$i days ago" +%d-%b-%Y`
	k=$(expr $i - 1)
	export Until_Date=`/bin/date --date="$k days ago" +%d-%b-%Y`
	echo -e "# $Until_Date\n" >> $CHANGELOG;

    # Cycle through all available repos
    for repo_path in $REPO_LIST; do
        if [ ! -d $repo_path ];then
            continue
        fi
        # Find commits between $CHANGELOG_DAYS dates
        GIT_LOG="$(git -C "$repo_path" \
            log --oneline \
            -n 1 \
            --after="$After_Date" --until="$Until_Date" \
            --pretty=tformat:"%x2A %s" \
            --abbrev-commit --abbrev=7 \
        )"
        [ -n "$GIT_LOG" ] && {
            echo -e "$GIT_LOG"
        } >> $CHANGELOG
    done
	echo -e "" >> $CHANGELOG;
done

cp $CHANGELOG ${OUT_DIR:-./out}/target/product/$DEVICE/
rm $CHANGELOG
echo -e "${GREEN}Done generating changelog for $DEVICE"

unset GREEN CHANGELOG DEVICE
